config/routes.rb
Rails.application.routes.draw do
  get "search", to: "search#index", as: :search
  get  "opml",        to: "opml#index",  as: :opml
  get  "opml/export", to: "opml#export", as: :export_opml
  post "opml/import", to: "opml#import", as: :import_opml

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  
  resources :articles do
    member do
      patch :toggle_read
      patch :toggle_starred
    end
    collection do
      patch :mark_all_read
      patch :mark_page_read
      get :sidebar_counts
    end
  end
  
  resources :categories
  resources :filters
  resources :feeds
  resources :dashboard, only: [:index]



  get "up" => "rails/health#show", as: :rails_health_check

  root "dashboard#index"
end

app/models/feed.rb
class Feed < ApplicationRecord
    has_many :articles, dependent: :destroy

    belongs_to :category

    validates :url, presence: true, uniqueness: true
    validates :name, presence: true

    # Set default category before validation if none is assigned to it
    before_validation :set_default_category, if: -> { category.nil? }

    def unread_count
        @unread_count || 0
    end

    private
    def set_default_category 
        self.category = Category.uncategorized
    end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[ show edit update destroy ]

  # GET /feeds or /feeds.json
  def index
    @feeds = Feed.includes(:category).order('categories.name, feeds.name, feeds.url')
    @categories = Category.all
  end

  # GET /feeds/1 or /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
    @categories = Category.all
  end

  # GET /feeds/1/edit
  def edit
    @categories = Category.all
  end

  # POST /feeds or /feeds.json
  def create
    @feed = Feed.new(feed_params)
    
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: "Feed was successfully created." }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1 or /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: "Feed was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1 or /feeds/1.json
  def destroy
    @feed.destroy!

    respond_to do |format|
      format.html { redirect_to feeds_path, notice: "Feed was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def feed_params
      params.expect(feed: [ :name, :url, :category_id ])
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_feed.html.erb
<div id="<%= dom_id feed %>" class="article_item">
  <div class="feed_name"><%= link_to feed.name, feed_path(feed) %></div>
  <div class="feed_url"><%= link_to feed.url, feed.url, target: "_blank" %></div>
  <div class="feeds_category"><%= feed.category.name %></div>
  <div class="feed_show"><%= link_to "Edit this feed", edit_feed_path(feed) %></div>
</div>
<style>

</style>

app/views/feeds/_form.html.erb
<%= form_with(model: feed) do |form| %>
  <% if feed.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :category_id, "Category", style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, 
        { prompt: "Select a category" }, 
        { class: "form-control" } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<% content_for :title, "Editing feed" %>

<h1>Editing feed</h1>

<%= render "form", feed: @feed %>

<br>

<div>
  <%= link_to "Show this feed", @feed %> |
  <%= link_to "Back to feeds", feeds_path %>
</div>

app/views/feeds/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Feeds" %>
<div class="page_header">
  <h1>Feeds</h1>    
  <div class="btn_new">
    <%= link_to "New feed", new_feed_path %>
  </div>
</div>

<div id="feeds" class="feeds">
  <% @feeds.each do |feed| %>
    <div class="feeds_item">
      <div class="feeds_category" style="background-color: <%= feed.category.color %>"><%= feed.category.name %></div>
      <div class="feeds_name"><%= feed.name %></div>
      <div class="feeds_url"><%= feed.url %></div>
      <div class="feeds_show"><%= link_to "Edit this feed", edit_feed_path(feed) %></div>
    </div>
  <% end %>
</div>

app/views/feeds/new.html.erb
<% content_for :title, "New feed" %>

<h1>New feed</h1>

<%= render "form", feed: @feed %>

<br>

<div>
  <%= link_to "Back to feeds", feeds_path %>
</div>

app/views/feeds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feed %>

<div>
  <%= link_to "Back to feeds", feeds_path %>

  <%= button_to "Destroy this feed", @feed, method: :delete %>
</div>