config/routes.rb
Rails.application.routes.draw do
  get "search", to: "search#index", as: :search
  get  "opml",        to: "opml#index",  as: :opml
  get  "opml/export", to: "opml#export", as: :export_opml
  post "opml/import", to: "opml#import", as: :import_opml

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  
  resources :articles do
    member do
      patch :toggle_read
      patch :toggle_starred
    end
    collection do
      patch :mark_all_read
      patch :mark_page_read
      get :sidebar_counts
    end
  end
  
  resources :categories
  resources :filters
  resources :feeds
  resources :dashboard, only: [:index]



  get "up" => "rails/health#show", as: :rails_health_check

  root "dashboard#index"
end

app/models/filter.rb
class Filter < ApplicationRecord
  has_many :articles

  after_create :apply_to_existing_articles
  before_destroy :unfilter_articles  # Changed from after_destroy to before_destroy
  
  # Returns a regex for this filter's term, treating * as wildcard
  def regex
    escaped = Regexp.escape(term).gsub("\\*", ".*")
    /#{escaped}/i
  end

  def matches_article?(article)
    return false if term.blank?

    title_match = title? && article.title.to_s.match?(regex)
    description_match = description? && article.description.to_s.match?(regex)

    title_match || description_match
  end

  private

  def apply_to_existing_articles
    Article.where(filtered: false).find_each do |article|
      if matches_article?(article)
        article.update!(filtered: true, filter_id: self.id)
      end
    end
  end

  def unfilter_articles
    Article.where(filter_id: self.id).update_all(filtered: false, filter_id: nil)
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_filter, only: %i[ show edit update destroy ]

  # GET /filters or /filters.json
  def index
    # @filters = Filter.all
    @filters = Filter.all
    @filters = Filter.left_joins(:articles)
                     .select("filters.*, COUNT(articles.id) AS articles_count")
                     .group("filters.id")
  end

  # GET /filters/1 or /filters/1.json
  def show
    # Get all articles that have been filtered out
    @filtered_articles = @filter.articles.order(published: :desc,id: :desc)
  end

  # GET /filters/new
  def new
    @filter = Filter.new
  end

  # GET /filters/1/edit
  def edit
  end

  # POST /filters or /filters.json
  def create
    @filter = Filter.new(filter_params)

    respond_to do |format|
      if @filter.save
        format.html { redirect_to @filter, notice: "Filter was successfully created." }
        format.json { render :show, status: :created, location: @filter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filters/1 or /filters/1.json
  def update
    respond_to do |format|
      if @filter.update(filter_params)
        format.html { redirect_to @filter, notice: "Filter was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @filter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1 or /filters/1.json
  def destroy
    @filter.destroy!

    respond_to do |format|
      format.html { redirect_to filters_path, notice: "Filter was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def filter_params
      params.expect(filter: [ :term, :title, :description ])
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_filter.html.erb
<div id="<%= dom_id filter %>">
  <p>
    <strong>Term:</strong>
    <%= filter.term %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= filter.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= filter.description %>
  </p>

</div>

app/views/filters/_form.html.erb
<%= form_with(model: filter) do |form| %>
  <% if filter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
        <% filter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :term, style: "display: block" %>
    <%= form.textarea :term %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.checkbox :title, { checked: true }, "1", "0" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.checkbox :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/filters/edit.html.erb
<% content_for :title, "Editing filter" %>

<h1>Editing filter</h1>

<%= render "form", filter: @filter %>

<br>

<div>
  <%= link_to "Show this filter", @filter %> |
  <%= link_to "Back to filters", filters_path %>
</div>

app/views/filters/index.html.erb
<% content_for :title, "Filters" %>

<div class="page_header filter_header">
  <h1>Filters</h1>
  <div class="btn_new">
    <%= link_to "New filter", new_filter_path %>
  </div>
</div>
<div id="filters" class="filters">
  <div class="filters_item">
    <div class="filters_item_info">
      <!-- There has to be a better way to do this... --> 
      (#)
    </div>
    <div class="filters_item_term">
      term
    </div>
    <div class="filters_item_title">
      in_title
    </div>
    <div class="filters_item_description">
      in_desc
    </div>
    <div class="filters_item_show">
      show
    </div>
  </div>
  <% @filters.each do |filter| %>
    <%#= render filter %>
    <div class="filters_item">
      <div class="filters_item_info">
        <!-- There has to be a better way to do this... --> 
        (<%= filter.articles_count %>)
      </div>
      <div class="filters_item_term">
        <%= filter.term %>
      </div>
      <div class="filters_item_title">
        <%= filter.title %>
      </div>
      <div class="filters_item_description">
        <%= filter.description %>
      </div>
      <div class="filters_item_show">
        <%= link_to "Show this filter", filter %>
      </div>
    </div>
  <% end %>
</div>

app/views/filters/new.html.erb
<% content_for :title, "New filter" %>

<h1>New filter</h1>

<%= render "form", filter: @filter %>

<br>

<div>
  <%= link_to "Back to filters", filters_path %>
</div>

app/views/filters/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @filter %>

<div>
  <%= link_to "Edit this filter", edit_filter_path(@filter) %> |
  <%= link_to "Back to filters", filters_path %>

  <%= button_to "Destroy this filter", @filter, method: :delete %>
</div>

<div class="filters_show_all">
<table border="1">
  <% @filtered_articles.each do |article| %>
    <tr>
      <td><div class="filters_show_articles_feed_name"><%= article.feed.name %></div></td>
      <td><div class="filters_show_article_title"><%= article.title %></div></td>
      <td><div class="filters_show_article_published"><%= article.published.in_time_zone("Eastern Time (US & Canada)") %></div></td>
    </tr>
  <% end %>
</table>
</div>

<style>
.filters_show_all {
  margin-top: 10px;
  margin-bottom: 10px;
}
.filters_show_all table {
  border-collapse: collapse;
}
.filters_show_all td {
  padding: 2px 4px;
 }
.filters_show_all {
  max-width: 90%;
  margin-left: auto;
  margin-right: auto;
}
.filters_show_article {
  border-radius: 12px;
  background-color: #333;
  color: #fff;
  padding: 3px 6px;
}
.filters_show_articles_feed_name,
.filters_show_article_published {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    max-width: 200px;
    height: 1rem;  
}
.filters_show_article_title {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    max-width: 500px;
    height: 1rem;
}
</style>