config/routes.rb
Rails.application.routes.draw do
  get "search", to: "search#index", as: :search
  get  "opml",        to: "opml#index",  as: :opml
  get  "opml/export", to: "opml#export", as: :export_opml
  post "opml/import", to: "opml#import", as: :import_opml

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  
  resources :articles do
    member do
      patch :toggle_read
      patch :toggle_starred
    end
    collection do
      patch :mark_all_read
      patch :mark_page_read
      get :sidebar_counts
    end
  end
  
  resources :categories
  resources :filters
  resources :feeds
  resources :dashboard, only: [:index]



  get "up" => "rails/health#show", as: :rails_health_check

  root "dashboard#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rss" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar">
    <div class="navbar-item <%= 'active' if current_page?(dashboard_path) %>">
      <%= link_to "Dashboard", dashboard_path %>
    </div>
    <div class="navbar-item <%= 'active' if current_page?(articles_path) %>">
      <%= link_to "Articles", articles_path %>
    </div>
    <div class="navbar-item <%= 'active' if current_page?(search_path) %>">
      <%= link_to "Search", search_path %>
    </div>
    <div class="navbar-item <%= 'active' if current_page?(categories_path) %>">
      <%= link_to "Categories", categories_path %>
    </div>
    <div class="navbar-item <%= 'active' if current_page?(feeds_path) %>">
      <%= link_to "Feeds", feeds_path %>
    </div>
    <div class="navbar-item <%= 'active' if current_page?(filters_path) %>">
      <%= link_to "Filters", filters_path %>
    </div>
    <div class="navbar-item <%= 'active' if current_page?(opml_path) %>">
      <%= link_to "OPML", opml_path %>
    </div>
  </div>
    <div class="page_container">
      <%= yield %>
    </div>
  </body>
</html>